### ISSUE TITLE
Reproduction issues on LLaMA3.1 (TOFU): checkpoint vs final‑model evaluation + epoch step‑count mismatch

### ISSUE THREAD

**Issue by ma-kjh** [locuslab/open-unlearning#88]
### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task
- [ ] My own task or dataset (give details below)

### Reproduction

Thank you for your excellent work on OpenUnlearning. I’m currently attempting to reproduce the results using the **LLaMA-2-7b-chat-hf** model and the **GradDiff** unlearning method on the **10% forget split** of the TOFU benchmark.

Here’s what I’ve done so far:

---

### 1. Experiment Configuration  
I created the following experiment config at:  
`/configs/experiment/unlearn/tofu/Llama-2-7b-chat-hf.yaml`:

```yaml
# @package _global_

defaults:
  - override /model: Llama-2-7b-chat-hf
  - override /trainer: GradAscent
  - override /data: unlearn
  - override /data/datasets@data.forget: TOFU_QA_forget
  - override /data/datasets@data.retain: TOFU_QA_retain
  - override /eval: tofu

model:
  model_args:
    pretrained_model_name_or_path: open-unlearning/tofu_Llama-2-7b-chat-hf_full

forget_split: forget10
retain_split: retain90
retain_logs_path: null

eval:
  tofu:
    forget_split: ${forget_split}
    retain_logs_path: ${retain_logs_path}
    overwrite: true
    
data:
  anchor: forget
  forget:
    TOFU_QA_forget: 
      args:
        hf_args:
          name: ${forget_split}
  retain:
    TOFU_QA_retain:
      args:
        hf_args:
          name: ${retain_split}

trainer:
  args:
    warmup_epochs: 1.0
    learning_rate: 1e-5
    weight_decay: 0.01
    num_train_epochs: 10

task_name: ???
```

---

### 2. Execution Command  
I ran the following command:

```bash
CUDA_VISIBLE_DEVICES=0,1 python src/train.py \
  --config-name=unlearn.yaml \
  experiment=unlearn/tofu/Llama-2-7b-chat-hf.yaml \
  forget_split=forget10 \
  retain_split=retain90 \
  trainer=GradDiff \
  task_name=Llama-2-7b-chat-hf-GradDiff \
  trainer.args.per_device_train_batch_size=4 \
  trainer.args.gradient_accumulation_steps=4
```

---

### 3. Evaluation Results  
At the final checkpoints (31 and 60), I obtained the following results:

**Checkpoint 31:**
```json
{
  "forget_Q_A_ROUGE": 0.5793,
  "retain_Q_A_ROUGE": 0.7175,
  "model_utility": 0.5869,
  "forget_Q_A_Prob": 0.6063,
  "retain_Q_A_Prob": 0.9013
}
```

**Checkpoint 60:**
```json
{
  "forget_Q_A_ROUGE": 0.4949,
  "retain_Q_A_ROUGE": 0.6398,
  "model_utility": 0.5714,
  "forget_Q_A_Prob": 0.4290,
  "retain_Q_A_Prob": 0.8337
}
```

---

### Problem  

When using a previous version of the codebase, I observed better forgetting and retention behavior under similar conditions.

I’m having trouble identifying what has changed between the previous implementation and the current one. Could you please advise if there are any known issues or differences in:
- Dataset preparation?
- Model loading?
- Trainer logic (e.g., `GradDiff`)?
- Evaluation configuration?

Any guidance or suggestions for troubleshooting this would be greatly appreciated.

Thank you very much in advance for your help!

### Expected behavior

![Image](https://github.com/user-attachments/assets/47fa07dc-6cad-4667-905a-3fcec9ced714)

The ROUGE scores shown in the figure could not be reproduced.
Could you please let me know what changes have been made compared to the previous codebase?

Although the above experiment was run for 10 epochs, I also observed similar trends with 5 epochs. Compared to the previous codebase, it seems that the influence of the forget loss is reduced — the ROUGE score on the forget set decreases gradually rather than showing a clear drop.

**Comment by molereddy** [comment]
Hi, this is due to the different finetuned target models. A target model is the model before the unlearning process starts, post initial finetuning on the TOFU dataset.
While updating to OpenUnlearning, we trained and provided all target models again, while using the same hyperparameters as the original ones from the paper (and got roughly equal initial checkpoint evaluations with the new target models as the original). But upon unlearning, with these models people have been reporting [[1](https://github.com/locuslab/open-unlearning/pull/72#issuecomment-2741536915)] that the same hyperparameters don't work anymore. A similar issue was raised and discussed at that link. You may have to tune your hyperparameters for this new target model to achieve equally good results.

For your research work, you may want to stick with the [original paper's target models](https://huggingface.co/locuslab/tofu_ft_llama2-7b) for Llama-7b. Though ideally, for updating the OpenUnlearning leaderboard, we plan to only use the [new versions](https://huggingface.co/open-unlearning/tofu_Llama-2-7b-chat-hf_full) of target models.

**Why target models differ**
Compared to the original TOFU repo, we're only aware of using different data preprocessing logic ([[2](https://github.com/locuslab/open-unlearning/blob/bed6430c4afda05ccc52a13fe44a4de77bf5ef58/src/data/utils.py#L14)] v/s [[3](https://github.com/locuslab/tofu/blob/bdc209ea7c6cc2e7079ea1afb6468d3ddcc65f8e/data_module.py#L8)]) in order to standardize the preprocessing and allow for dynamic max batch length padding. Other than that the differences are mostly in the hardware usage, which shouldn't matter significantly.
We are looking into if we've missed anything more.

**Comment by ma-kjh** [comment]
Thank you for the quick response. I’ll give it a try and leave a comment if I run into any issues.

**Comment by ma-kjh** [comment]
@molereddy Hello, I have one more question, so I'm leaving a comment here. I might have missed it, but could you please let me know how to measure `forget_quality` using an already generated TOFU_EVAL.json file? I remember this was included in the original TOFU code, but it seems a bit hard to find in this repository. Thank you so much.

**Comment by molereddy** [comment]
Our readme includes instructions for downloading this data using setup_data.py. See https://github.com/locuslab/open-unlearning/issues/73

**Comment by ma-kjh** [comment]
Thank you so much.

**Comment by Dornavineeth** [comment]
@ma-kjh Could you please share:

1. The script and configuration files you used for evaluation.
2. The results you're obtaining. Minor differences are fine, especially when running on different machines.

**Note**: I recommend pulling the latest updates and re-run setup_data.py. In our recent PR, we introduced a fixed seed for evaluation as well. However,  using the same seed does not guarantee exactly same results across different machines, due to potential variations at the hardware or system level.

**Comment by ma-kjh** [comment]
I'm noticing that the evaluation results from checkpoint-last-epoch/TOFU_eval.json or TOFU_summary.json differ from the results I get when I reload the final checkpoint and run evaluation again (e.g., eval0). I'm wondering why this discrepancy occurs — is there something I might be missing?

/.hydra/config.yaml
```
model:
  model_args:
    pretrained_model_name_or_path: open-unlearning/tofu_Llama-3.2-1B-Instruct_full
    attn_implementation: flash_attention_2
    torch_dtype: bfloat16
  tokenizer_args:
    pretrained_model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
  template_args:
    apply_chat_template: true
    system_prompt: You are a helpful assistant.
    system_prompt_with_special_tokens: '<|begin_of_text|><|start_header_id|>system<|end_header_id|>


      You are a helpful assistant.<|eot_id|>'
    user_start_tag: '<|start_header_id|>user<|end_header_id|>


      '
    user_end_tag: <|eot_id|>
    asst_start_tag: '<|start_header_id|>assistant<|end_header_id|>


      '
    asst_end_tag: <|eot_id|>

trainer:
  handler: GradDiff
  args:
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 16
    gradient_accumulation_steps: 2
    learning_rate: 1.0e-05
    bf16: true
    bf16_full_eval: true
    logging_steps: 5
    output_dir: ${paths.output_dir}
    logging_dir: ${trainer.args.output_dir}/logs
    report_to: tensorboard
    ddp_find_unused_parameters: None
    gradient_checkpointing: false
    optim: paged_adamw_32bit
    save_strategy: 'no'
    save_only_model: true
    weight_decay: 0.01
    do_train: true
    do_eval: true
    eval_on_start: true
    eval_strategy: epoch
    num_train_epochs: 10
    seed: 0
    warmup_epochs: 1.0
    remove_unused_columns: false
  method_args:
    gamma: 0.1
    alpha: 0.9
    retain_loss_type: NLL

data:
  forget:
    TOFU_QA_forget:
      handler: QADataset
      args:
        hf_args:
          name: ${forget_split}
          split: train
          path: locuslab/TOFU
        question_key: question
        answer_key: answer
        max_length: 512
  retain:
    TOFU_QA_retain:
      handler: QADataset
      args:
        hf_args:
          name: ${retain_split}
          split: train
          path: locuslab/TOFU
        question_key: question
        answer_key: answer
        max_length: 512
  anchor: forget
collator:
  DataCollatorForSupervisedDataset:
    handler: DataCollatorForSupervisedDataset
    args:
      padding_side: right
eval:
  tofu:
    metrics:
      forget_quality:
        pre_compute:
          forget_truth_ratio:
            pre_compute:
              forget_Q_A_PARA_Prob:
                datasets:
                  TOFU_QA_forget_para:
                    handler: QADataset
                    args:
                      hf_args:
                        name: ${eval.tofu.forget_split}_perturbed
                        split: train
                        path: locuslab/TOFU
                      question_key: question
                      answer_key: paraphrased_answer
                      max_length: 512
                collators:
                  DataCollatorForSupervisedDataset:
                    handler: DataCollatorForSupervisedDataset
                    args:
                      padding_side: right
                      index: index
                handler: probability
                batch_size: 32
                access_key: correct
              forget_Q_A_PERT_Prob:
                datasets:
                  TOFU_QA_forget_pert:
                    handler: QADataset
                    args:
                      hf_args:
                        name: ${eval.tofu.forget_split}_perturbed
                        split: train
                        path: locuslab/TOFU
                      question_key: question
                      answer_key: perturbed_answer
                      max_length: 512
                collators:
                  DataCollatorForSupervisedDataset:
                    handler: DataCollatorForSupervisedDataset
                    args:
                      padding_side: right
                      index: index
                handler: probability
                batch_size: 32
                access_key: wrong
            handler: truth_ratio
            aggregator: closer_to_1_better
            access_key: forget
        reference_logs:
          retain_model_logs:
            path: ${eval.tofu.retain_logs_path}
            include:
              forget_truth_ratio:
                access_key: retain
        handler: forget_quality
      forget_Q_A_Prob:
        datasets:
          TOFU_QA_forget:
            handler: QADataset
            args:
              hf_args:
                name: ${eval.tofu.forget_split}
                split: train
                path: locuslab/TOFU
              question_key: question
              answer_key: answer
              max_length: 512
        collators:
          DataCollatorForSupervisedDataset:
            handler: DataCollatorForSupervisedDataset
            args:
              padding_side: right
              index: index
        handler: probability
        batch_size: 32
      forget_Q_A_ROUGE:
        datasets:
          TOFU_QA_forget:
            handler: QADataset
            args:
              hf_args:
                name: ${eval.tofu.forget_split}
                split: train
                path: locuslab/TOFU
              question_key: question
              answer_key: answer
              max_length: 512
              predict_with_generate: true
        collators:
          DataCollatorForSupervisedDataset:
            handler: DataCollatorForSupervisedDataset
            args:
              padding_side: left
              index: index
        generation_args:
          do_sample: false
          top_p: null
          temperature: null
          max_new_tokens: 200
          use_cache: true
        handler: rouge
        rouge_type: rougeL_recall
        batch_size: 32
```

**Comment by Dornavineeth** [comment]
Can you share the bash command you used for 
1. Unlearning 
2. Evaluating it after unlearning

Also what do you mean by eval0?

**Comment by ma-kjh** [comment]
```
CUDA_VISIBLE_DEVICES=0,1 python src/train.py \
--config-name=unlearn.yaml experiment=unlearn/tofu/default   \ 
forget_split=forget10 retain_split=retain90 \
trainer=GradDiff_01_09 task_name=Llama-3.2-1B-Instruct-GradDiff-gamma-0.1-aplha-0.9-ep10 \
trainer.args.per_device_train_batch_size=8 \ 
trainer.args.gradient_accumulation_steps=2 \ 
trainer.args.num_train_epochs=10
```

GradDiff_01_09
```
defaults:
  - finetune

handler: GradDiff
method_args:
  gamma: 0.1
  alpha: 0.9
  retain_loss_type: NLL
```

```
/open-unlearning/saves/unlearn/Llama-3.2-1B-Instruct-GradDiff-gamma-0.1-aplha-0.9-ep10/checkpoint-0/evals
```
Also what do you mean by eval0?

Sorry, I meant the evaluation result of checkpoint-0 (eval0).
